### ISSUE TITLE
Ingredient scoring with optional ingredients

### ISSUE THREAD

**Issue by Thorinwasher** [BreweryTeam/BreweryX#139]
This idea originates from snoweh_ (discord name).

Have the ingredient score depend on whaty type of ingredients are being added. Here's the syntax of how it could be achieved.
```yml
ingredients:
  - + wheat/12 || ItemsAdder:barley/8 
  - ++ ItemsAdder:barley_t2/8
  - +++ ItemsAdder:barley_t3/6
``
I copied over the syntax that is used for lore depending on score. In this case, if an ingredient is part of the bad quality secton, then it is going to provide a bad score for the resulting brew, same with good section and good score and so on.

The `||` symbol means that either of the provided ingredients are allowed. For simplicity on our end, I say no mixing between those ingredients are allowed. Here's another usecase, say only the finest of a brew has ingredient x:
```yml
ingredients:
  - boring_mandatory_ingredient/9
  - +++ ingredient_x/1
```
Then the quality can not be perfect except if the brew contains ingredient x.
